### ISSUE TITLE
Updated from 2.11.3 to 2.12.0 and Fabrication no longer finds fabricators

### ISSUE THREAD

**Issue by ninjarobert** [paulelliott/fabrication#237]
Hello,

This morning I updated Fabrication to its newest version from 2.11.3. My next test run threw errors on every test that used a Fabricator. 

I then locked Fabrication back to 2.11.3 and the errors went away. I changed nothing else significant. All my fabricators are in test/fabricators as before.

Any ideas what might have changed?

**Comment by paulelliott** [comment]
What ruby version are you using and what kind of project is it? Rails version, etc.

**Comment by ninjarobert** [comment]
It is a Rails 4.2 app under Ruby 2.2.0.

The test environment is setup with the Minitest-Rails gem.

**Comment by paulelliott** [comment]
Can you provide the trace on the first error encountered when you run the suite?

**Comment by ninjarobert** [comment]
```
Taggable#test_0001_processes a tag list into taggable objects:
Fabrication::UnknownFabricatorError: No Fabricator defined for 'customer'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:38:in `schematic'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:29:in `create'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication.rb:62:in `Fabricate'
    /Users/robertrouse/code/api/test/models/concerns/taggable_test.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by paulelliott** [comment]
Where are your fabricators located within the project?

**Comment by ninjarobert** [comment]
test/fabricators

**Comment by paulelliott** [comment]
If you go into the rails console and try to `Fabricate.build(:customer)`, do you see a more helpful error message?

**Comment by ninjarobert** [comment]
For that one, yes. I can see why that one is now failing, but it wasn't before.

I have one for an employee class that doesn't change though

```
[3] pry(main)> Fabricate.build(:employee)
Fabrication::UnknownFabricatorError: No Fabricator defined for 'employee'
from /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:38:in `schematic'
```

```
Error:
Web::V1::TaskAssignmentsController#test_0005_rejects inaccessible attribute updates:
Fabrication::UnknownFabricatorError: No Fabricator defined for 'employee'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:38:in `schematic'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:29:in `create'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication.rb:62:in `Fabricate'
    /Users/robertrouse/code/api/test/fabricators/account_fabricator.rb:6:in `block (2 levels) in <top (required)>'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:33:in `instance_exec'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:33:in `block in execute_callbacks'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:33:in `each'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:33:in `execute_callbacks'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:15:in `build'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/generator/base.rb:20:in `create'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/schematic/definition.rb:75:in `block in fabricate'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/schematic/definition.rb:74:in `instance_eval'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication/schematic/definition.rb:74:in `fabricate'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabricate.rb:29:in `create'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fabrication-2.12.0/lib/fabrication.rb:62:in `Fabricate'
    /Users/robertrouse/code/api/test/controllers/web/v1/task_assignments_controller_test.rb:5:in `block (2 levels) in <top (required)>'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `call'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_setup_callbacks'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
    /Users/robertrouse/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:825:in `before_setup'
```

**Comment by paulelliott** [comment]
Are you fabricating any classes that are contained within modules?

**Comment by ninjarobert** [comment]
No. All models are top level

**Comment by paulelliott** [comment]
Can you provide the definition of the `employee` fabricator?

**Comment by ninjarobert** [comment]
```
Fabricator(:employee) do
  account
  name { Faker::Name.name }
  email_address { Faker::Internet.safe_email }
  password { Faker::Internet.password }
  username { Faker::Internet.user_name(5..10, ['_']) }
end
```

**Comment by ninjarobert** [comment]
I'm willing to accept it's something in my environment, so if this is becoming time consuming, I can try to fix it myself. I was hoping you'd see something quickly.

Sorry!

**Comment by paulelliott** [comment]
The fact that it was working before you upgraded makes me think it is an issue in the new version. There were a few changes in that release that could potentially have had negative consequences, but you don't seem to have any of those scenarios. Usually when a fabricator can't be found, it is because there was an issue during the load. Fabricators are not loaded until you actually try to fabricate something, so this would typically happen during your first test execution.

The actual definitions are stored in a hash which you can access directly at `Fabrication.manager.schematics`. If you try to fabricate something in the console and then check that hash, you should see stuff in there. If not, there is an issue somewhere. It loads the fabricators from the file system alphabetically, so if you only see part of them there you can track down the offender that way.

If you need some more help I would be happy to screen share with you later today and take a closer look.

**Comment by ninjarobert** [comment]
Aha, Fabrication.manager.schematics was the key here. Thanks.

I was unaware the fabricators were loaded in any particular order, so I missed that it was all connected to the same thing that caused the Customer fabricator to fail as well.

I had a CalendarSettings model (pulled from a previous app) that Fabrication was tripping over during load (since it was plural and not singular).

It didn't fail with the previous version of Fabrication but does with the new version.

So it was surprising, but not actually a problem with Fabrication itself. 

Thanks for working through this with me!

**Comment by paulelliott** [comment]
Glad you got it working!

We changed to use ActiveSupport's `classify` method when turning fabricator names into classes, so that is likely why it is behaving differently now. I think the behavior is correct now and the previous behavior was a bug.

Thanks!
