### ISSUE TITLE
ActiveRecord::UnknownAttributeError: unknown attribute: Fabricate

### ISSUE THREAD

**Issue by tilumi** [paulelliott/fabrication#254]
user_fabricator:

```
Fabricator(:user) do
  email { Faker::Internet.email }
  name { Faker::Name.name }
end
```

category_fabricator:

```
Fabricator(:category) do
  transient user: Fabricate(:user)
  user { |attrs| attrs[:user] }  
  category { Faker::Lorem.characters(5) }
  type 1
  update_time Time.zone.now
end
```

record_fabricator:

```
Fabricator(:record) do
  transient user: Fabricate(:user)
  user {|attrs| attrs[:user]}
  category { |attrs| Fabricate(:category, user: attrs[:user]).hash_key}  
end
````

seed.rb: 

````
lucasmf = Fabricate(:user)
record = Fabricate(:record, user: lucasmf)
````

I get following errors:

```
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute: Fabricate
/Users/lucasmf/git/andromoney_server/spec/fabricators/record_fabricator.rb:8:in `block (2 levels) in <top (required)>'
/Users/lucasmf/git/andromoney_server/db/seeds.rb:10:in `<top (required)>'
NoMethodError: undefined method `Fabricate=' for #<Category:0x007fb06a058dc8>
/Users/lucasmf/git/andromoney_server/spec/fabricators/record_fabricator.rb:8:in `block (2 levels) in <top (required)>'
/Users/lucasmf/git/andromoney_server/db/seeds.rb:10:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

May I ask what the cause of the error and how to fix it?? Thanks~

**Comment by tilumi** [comment]
I found the cause is form 
```
transient user: Fabricate(:user)
```
It seems using Fabricate as default value is not feasible??

**Comment by tilumi** [comment]
And I found passing Model as transient attribute won't work
After removing the default value of transient :user to avoid the error, then executing rake db:seed, the record, category and subcategory didn't associated with user.

**Comment by paulelliott** [comment]
Declaring the transient will tell Fabrication not to set the attribute on the underlying model. If you specify the field later like I've done here, it will automatically expand to `Fabricate(:user)` unless you pass in an override.

Give this a shot and let me know how it goes!

```
Fabricator(:category) do
  transient :user
  user
  category { Faker::Lorem.characters(5) }
  type 1
  update_time { Time.zone.now }
end

Fabricator(:record) do
  transient :user
  user
  category { |attrs| Fabricate(:category, user: attrs[:user]).hash_key}  
end
```
