### ISSUE TITLE
Weird error with simple belongs_to association

### ISSUE THREAD

**Issue by sauronnikko** [paulelliott/fabrication#268]
Hi. I'm working with Rails `5.0.0.beta2` in API mode. My `fabrication` gem version is `2.14.1`. I've got two models, two fabricators and a `seed.rb` file:

```ruby
#app/models/competition.rb

# == Schema Information
#
# Table name: competitions
#
#  id           :integer          not null, primary key
#  classroom_id :integer
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Competition < ApplicationRecord

  belongs_to :classroom, inverse_of: :competitions

  validates :classroom, presence: true
  validates :name, presence: true, uniqueness: { scope: [:classroom] }

end

# app/models/classroom.rb
# == Schema Information
#
# Table name: classrooms
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Classroom < ApplicationRecord

	has_many :competitions, dependent: :destroy, inverse_of: :classroom

  validates :name, presence: true, uniqueness: :true

end

# spec/fabricators/classroom.rb

Fabricator(:classroom) do
  name { Faker::Lorem.sentence(2) }
  competitions(fabricator: :competition, rand: 4)
end


#spec/fabricators/competition_fabricator.rb
Fabricator(:competition) do
  classroom
  name { Faker::Lorem.sentence(3) }
end

# db/seed.rb
Fabricate.times(1, :classroom)
```

When executing `rake db:seed` with an empty database (just the schema), I'm getting the following error:

```shell
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:33:in `create'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication.rb:63:in `Fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:112:in `block in generate_value'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:40:in `instance_exec'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:40:in `execute'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:28:in `processed_value'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:102:in `block in process_attributes'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:101:in `each'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:101:in `process_attributes'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:6:in `build'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:20:in `create'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:78:in `block in fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:77:in `instance_eval'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:77:in `fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:33:in `create'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication.rb:63:in `Fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:112:in `block in generate_value'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:40:in `instance_exec'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:40:in `execute'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:26:in `block in processed_value'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/range/each.rb:5:in `each'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/range/each.rb:5:in `each'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:26:in `map'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/attribute.rb:26:in `processed_value'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:102:in `block in process_attributes'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:101:in `each'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:101:in `process_attributes'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:6:in `build'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/generator/base.rb:20:in `create'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:78:in `block in fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:77:in `instance_eval'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication/schematic/definition.rb:77:in `fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:33:in `create'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabrication.rb:63:in `Fabricate'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:3:in `block in times'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:3:in `times'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:3:in `each'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:3:in `map'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/fabrication-2.14.1/lib/fabricate.rb:3:in `times'
/home/sauronnikko/Sites/teams-api/db/seeds.rb:24:in `<top (required)>'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `block in load'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/railties-5.0.0.beta2/lib/rails/engine.rb:549:in `load_seed'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activerecord-5.0.0.beta2/lib/active_record/tasks/database_tasks.rb:261:in `load_seed'
/home/sauronnikko/.rvm/gems/ruby-2.2.3@rails5.0/gems/activerecord-5.0.0.beta2/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

```

I didn't paste the whole error because it's huge. Notice also how it seems to repeat itself. Additionally, if I remove `classroom` from the `Competition` fabricator, the `rake db:seed` command works but I think I'm not supposed to do that.

**Comment by paulelliott** [comment]
The issue is you have a circular relationship in your fabricators. You can override it by nulling out the `classroom` when you generate the list of `competitions`.
```
Fabricator(:classroom) do
  name { Faker::Lorem.sentence(2) }
  competitions(rand: 4) { Fabricate.build(:competition, classroom: nil) }
end
```
